//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuicompressor_gui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompressorVersion {
            get {
                return ((string)(this["CompressorVersion"]));
            }
            set {
                this["CompressorVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Auto Detect]")]
        public string JavaPath {
            get {
                return ((string)(this["JavaPath"]));
            }
            set {
                this["JavaPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("utf-8")]
        public string ArgCharset {
            get {
                return ((string)(this["ArgCharset"]));
            }
            set {
                this["ArgCharset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public decimal ArgLineBreak {
            get {
                return ((decimal)(this["ArgLineBreak"]));
            }
            set {
                this["ArgLineBreak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArgJsNoMunge {
            get {
                return ((bool)(this["ArgJsNoMunge"]));
            }
            set {
                this["ArgJsNoMunge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArgJsPreserveSemicolon {
            get {
                return ((bool)(this["ArgJsPreserveSemicolon"]));
            }
            set {
                this["ArgJsPreserveSemicolon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArgJsDisableOptimizations {
            get {
                return ((bool)(this["ArgJsDisableOptimizations"]));
            }
            set {
                this["ArgJsDisableOptimizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte ArgType {
            get {
                return ((byte)(this["ArgType"]));
            }
            set {
                this["ArgType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutputSepearatedFiles {
            get {
                return ((bool)(this["OutputSepearatedFiles"]));
            }
            set {
                this["OutputSepearatedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputSepearatedFilePrefix {
            get {
                return ((string)(this["OutputSepearatedFilePrefix"]));
            }
            set {
                this["OutputSepearatedFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".min")]
        public string OutputSepearatedFileSuffix {
            get {
                return ((string)(this["OutputSepearatedFileSuffix"]));
            }
            set {
                this["OutputSepearatedFileSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputCombinedFiles {
            get {
                return ((bool)(this["OutputCombinedFiles"]));
            }
            set {
                this["OutputCombinedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputShowAsText {
            get {
                return ((bool)(this["OutputShowAsText"]));
            }
            set {
                this["OutputShowAsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte OutputEncoding {
            get {
                return ((byte)(this["OutputEncoding"]));
            }
            set {
                this["OutputEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputSepearatedFileOverwrite {
            get {
                return ((bool)(this["OutputSepearatedFileOverwrite"]));
            }
            set {
                this["OutputSepearatedFileOverwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutputShowAsTextPrettyPrint {
            get {
                return ((bool)(this["OutputShowAsTextPrettyPrint"]));
            }
            set {
                this["OutputShowAsTextPrettyPrint"] = value;
            }
        }
    }
}
